import os
import requests
from github import Github, Auth
from datetime import datetime
import re

def main():
    print("=== Master AI Guardian Started ===")

    api_key = os.environ.get("CLAUDE_API_KEY")
    github_token = os.environ.get("AGENT_GITHUB_TOKEN")

    if not api_key or not github_token:
        print("ERROR: Missing API keys!")
        return

    user_command = os.environ.get("GUARDIAN_COMMAND", "")
    user_command_lower = user_command.lower()

    # === New Flow: Approve issue #X and create PR ===
    if "approve issue" in user_command_lower and "create pr" in user_command_lower:
        print("Processing approval and creating Pull Request...")

        # Extract Issue number
        match = re.search(r"#(\d+)", user_command)
        if not match:
            print("Please use format: Approve issue #5 and create PR")
            return

        issue_number = int(match.group(1))

        try:
            auth = Auth.Token(github_token)
            g = Github(auth=auth)
            repo = g.get_repo("AllahRakhha/SavingsClub")  # Change if needed

            # Get the Issue
            issue = repo.get_issue(issue_number)

            # Create new branch
            base = repo.get_branch("main")
            branch_name = f"ai-guardian-pr-{datetime.now().strftime('%Y%m%d%H%M')}"
            repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base.commit.sha)

            # Create a markdown file with suggestions
            file_name = f"ai-improvement-{datetime.now().strftime('%Y%m%d%H%M')}.md"
            file_path = f".github/{file_name}"

            file_content = f"""# AI Guardian Suggestions from Issue #{issue_number}

**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}

**Original Issue:** #{issue_number}

---

{issue.body}

---

**Note:** These are suggestions generated by Master AI Guardian.
Please review before merging.
"""

            repo.create_file(
                path=file_path,
                message=f"AI Guardian: Approved suggestions from Issue #{issue_number}",
                content=file_content,
                branch=branch_name
            )

            # Create Pull Request
            pr_title = f"AI Guardian Suggestions from Issue #{issue_number}"
            pr_body = f"**This PR contains approved suggestions from Issue #{issue_number}**\n\n**Approved by:** {user_command}"

            pr = repo.create_pull(title=pr_title, body=pr_body, head=branch_name, base="main")
            print(f"✅ Pull Request created successfully: {pr.html_url}")

        except Exception as e:
            print(f"❌ Failed to create Pull Request: {e}")
        return

    # Normal flow (you can expand this later with full audit logic)
    print("No matching command found. Running normal flow...")

if __name__ == "__main__":
    main()
